# Generated by Django 4.0.4 on 2022-06-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0002_alter_player_email_alter_vehicle_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
