# Generated by Django 4.0.4 on 2022-06-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0003_weapons_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maps',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='throwable',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
