# Generated by Django 4.0.4 on 2022-06-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0004_equipment_image_maps_link_throwable_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='armor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapons',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='reducedamage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
