# Generated by Django 4.0.4 on 2022-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0005_equipment_armor_weapons_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='damage',
            field=models.IntegerField(null=True),
        ),
    ]
