# Generated by Django 4.0.4 on 2022-06-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0006_weapons_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ocupant',
            field=models.IntegerField(null=True),
        ),
    ]
