# Generated by Django 4.0.4 on 2022-06-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0007_vehicle_health_vehicle_ocupant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Equipament',
        ),
    ]
