# Generated by Django 4.0.4 on 2022-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0008_rename_equipment_equipament'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='steam',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
