# Generated by Django 4.0.4 on 2022-06-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPubg', '0011_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='castTime',
            field=models.IntegerField(null=True),
        ),
    ]
